# https://github.com/qodo-ai/pr-agent/tree/main/pr_agent/settings
[config]
model="openai/MiniMax-M2.1" # for litellm, need to use openai/ prefix
fallback_models=["openai/MiniMax-M2.1-lightning", "openai/MiniMax-M2"]
custom_model_max_tokens=204800
response_language="zh-CN"